### PR TITLE
Unlock Wallet Implemented-Issue#68

### PR DESCRIPTION
**Pull request by kashyap2690**
Unlock Wallet implemented as per https://github.com/LIMXTEC/BitSend/issues/68

### CODE REVIEW

**Comment by limxdev** [comment]
Thank you write me please via Bitcointalk "Limx Dev" We want to pay a bounty for your work.

**Comment by joshafest** [comment]
@kashyap Prajapathi, bro contact us ... I am indian too

**Comment by joshafest** [comment]
@kashyap2690

**Comment by kashyap2690** [comment]
@limxdev  Thanks. I have written you via Bitcointalk.
@joshafest Great!!

**Pull request merged**
