### PR TITLE
Merge pull request #1 from LIMXTEC/master

### PR DESCRIPTION
**Pull request by JSponaugle**
Update BitSend

### CODE REVIEW

**Comment by limxdev** [comment]
Hello, thank you for your commit. Did you have tested it?

Kind Regards Christian

**Comment by JSponaugle** [comment]
Hello, This has been tested and is working.
Thanks, Jason (MasterNodes.Pro)

**Comment by joshafest** [comment]
you edited wrong file, darksend has now nothing to do with current code, or your pull was to old v1.2.7?

**Comment by joshafest** [comment]
@JSponaugle 
https://github.com/LIMXTEC/BitSend/blob/master/src/rpc/mining.cpp#L948 
here you go

**Comment by JSponaugle** [comment]
@joshafest I must still be behind on the Main Fork. I will close this and update my fork and fix the correct lines.

**Pull request closed without merging**
